/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function metrohash128(data: string, seed: number): string
export declare function metrohash64(data: string, seed: number): string
